export { default as DjFeatured } from "./DjFeatured";
export { default as DjHero } from "./DjHero";
export { default as DjWhy } from "./DjWhy";
export { default as HomeCorporate } from "./HomeCorporate";
export { default as HomeExplore } from "./HomeExplore";
export { default as HomeHero } from "./HomeHero";
export { default as Reviews } from "./Reviews";
export { default as VrGames } from "./VrGames";
export { default as VrSocialEvents } from "./VrSocialEvents";
